# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GrabMe' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GrabMe

  pod 'Kingfisher', '~> 6.0'

  target 'GrabMeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GrabMeUITests' do
    # Pods for testing
  end

end
